### ISSUE TITLE
we don't have dataset and datafile

### ISSUE THREAD

**Issue by yiyouweijin** [YZS666/A-Method-for-Solving-the-FS-SEI-Problem#1]
To run the code, we need the file '/data/yaozs/dataset/LoRa_dataset/Train/dataset_training_no_aug.h5'

**Comment by YZS666** [comment]
Hello:
&nbsp; &nbsp; The LoRa dataset link we use in this article is https://ieee-dataport.org/open-access/lorarffidataset.&nbsp;Hoping my answer is helpful to you.
Best Regards
Zhisheng Yao

College of Telecommunications &amp; Information Engineering

Nanjing University of Posts and&nbsp;Telecommunications

No. 66 Xinmofan Road, Nanjing 210003, China





曙光丶灬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YZS666/A-Method-for-Solving-the-FS-SEI-Problem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月20日(星期五) 中午12:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[YZS666/A-Method-for-Solving-the-FS-SEI-Problem] we don't have dataset and datafile (Issue #1)





 
To run the code, we need the file '/data/yaozs/dataset/LoRa_dataset/Train/dataset_training_no_aug.h5'

**Comment by yiyouweijin** [comment]
thank you
